server:
    port: 8085
management:
    endpoints:
        web:
            exposure:
                include: "*"

    endpoint:
        hystrix:
            stream:
                enabled: true
hystrix:
    dashboard:
        proxy-stream-allow-list: "*"
